site_name: SIP Framework Documentation
site_description: 'Documentation for using & developing with the SIP Framework'
site_author: 'x1F'
repo_url: 'https://github.com/IKOR-GmbH/sip-framework'
edit_uri: 'edit/main/docs/'
copyright:  © Copyright 2021-2025, <a href="https://x1f.one">x1F GmbH</a> & contributors

nav:
    - Introduction: README.md
    - Installation Guide: installation.md
    - Archetype: archetype.md
    - Core: core.md
    - Declarative Structure: declarative.md
    - Integration Starter: integration-starter.md
    - Starter Parent: starter-parent.md
    - Security: security.md
    - Test Kit: test-kit.md
    - Test Kit Declarative: test-kit-declarative.md
    - SOAP Starter: soap-starter.md
    - Maven Plugin: maven-plugin.md
    - Framework Version Upgrade: framework_version_upgrade.md
    - License: license.md
    - Contribution Guidelines: CONTRIBUTING.md
    - Code Of Conduct: CODE_OF_CONDUCT.md
    - Changelog: changelog.md
    - JavaDoc Latest Development: './javadoc/latest/index.html'
    # JAVADOC_RELEASES sed marker, do not delete
    - JavaDoc 4.5.0: './javadoc/4.5.0/index.html'
    - JavaDoc 4.4.2: './javadoc/4.4.2/index.html'
    - JavaDoc 4.4.1: './javadoc/4.4.1/index.html'
    - JavaDoc 4.4.0: './javadoc/4.4.0/index.html'
    - JavaDoc 4.3.1: './javadoc/4.3.1/index.html'
    - JavaDoc 4.3.0: './javadoc/4.3.0/index.html'
    - JavaDoc 4.2.0: './javadoc/4.2.0/index.html'
    - JavaDoc 4.1.0: './javadoc/4.1.0/index.html'
    - JavaDoc 4.0.1: './javadoc/4.0.1/index.html'
    - JavaDoc 4.0.0: './javadoc/4.0.0/index.html'
    - JavaDoc 3.6.2: './javadoc/3.6.2/index.html'
    - JavaDoc 3.6.1: './javadoc/3.6.1/index.html'
    - JavaDoc 3.6.0: './javadoc/3.6.0/index.html'
    - JavaDoc 3.5.0: './javadoc/3.5.0/index.html'
    - JavaDoc 3.4.0: './javadoc/3.4.0/index.html'
    - JavaDoc 3.3.0: './javadoc/3.3.0/index.html'
    - JavaDoc 3.2.0: './javadoc/3.2.0/index.html'
    - JavaDoc 3.1.0: './javadoc/3.1.0/index.html'
    - JavaDoc 3.0.0: './javadoc/3.0.0/index.html'
    - JavaDoc 2.4.0: './javadoc/2.4.0/index.html'
    - JavaDoc 2.3.0: './javadoc/2.3.0/index.html'
    - JavaDoc 2.2.0: './javadoc/2.2.0/index.html'
    - JavaDoc 2.1.0: './javadoc/2.1.0/index.html'
    - JavaDoc 2.0.2: './javadoc/2.0.2/index.html'
    - JavaDoc 2.0.0: './javadoc/2.0.0/index.html'
    - JavaDoc 1.0.0: './javadoc/1.0.0/index.html'
    - Find out more about x1F: 'https://www.x1f.one'
    - Impressum: 'https://www.x1f.one/impressum/'



theme:
  name: 'readthedocs'
  language: 'en'
  include_homepage_in_sidebar: True
  collapse_navigation: false

docs_dir: 'docs'

extra_css:
    - css/extra.css

extra_javascript:
    - javascript/javadoc_menu_dropdown.js
    - javascript/copy_to_clipboard.js

markdown_extensions:
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
