<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.ikor.sip.foundation</groupId>
    <artifactId>sip-framework</artifactId>
    <version>4.0.0</version>
    <packaging>pom</packaging>


    <distributionManagement>
        <relocation>
            <groupId>one.x1f.sip.foundation</groupId>
        </relocation>
    </distributionManagement>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>https://raw.githubusercontent.com/IKOR-GmbH/sip-framework/develop/LICENSE</url>
        </license>
    </licenses>

    <modules>
        <module>sip-core</module>
        <module>sip-security</module>
        <module>sip-integration-starter</module>
        <module>sip-starter-parent</module>
        <module>sip-archetype</module>
        <module>sip-test-kit</module>
        <module>sip-maven-plugin</module>
        <module>sip-soap-starter</module>
    </modules>
</project>
