#set( $dollar = '$' )
spring:
  application:
    name: ${projectName}
  threads:
    virtual:
      enabled: true
  config:
    import:
      - optional:classpath:/sip-security-config.yaml
#if (${useSipCloudFramework} == "y" or ${useSipCloudFramework} == "Y")
      - classpath:/sip-cloud-config.yaml
#end

camel:
  rest:
    component: servlet
    binding-mode: json
    data-format-property[prettyPrint]: true
    context-path: /adapter
    host-name-resolver: none
    use-x-forward-headers: true
    api-context-path: /api-doc
    api-context-route-id: api-docs-route-id
    api-property[api.title]: ${dollar}{spring.application.name:${projectName}}
    api-property[api.version]: @project.version@

# Template for REST authentication configuration
#  authentication:
#    disable-csrf:
#    auth-providers:
#      - classname:
#        ignored-endpoints:
#        validation:
#          classname:
#          file-path:


