# Manually provided license information for dependencies that inherit
# their license from a parent POM (net.shibboleth.parent / opensaml-parent)
# and are therefore not picked up automatically by license-maven-plugin.
#
# Format: groupId--artifactId--version=License Name

net.shibboleth--shib-security--9.1.6=Apache License, Version 2.0
net.shibboleth--shib-velocity--9.1.6=Apache License, Version 2.0
org.opensaml--opensaml-saml-impl--5.1.6=Apache License, Version 2.0
org.opensaml--opensaml-security-api--5.1.6=Apache License, Version 2.0
org.opensaml--opensaml-xacml-saml-api--5.1.6=Apache License, Version 2.0
