name: Java / Docs CI

on:
  workflow_dispatch:
    inputs:
      do-release:
        description: indicates if a release should be done
        required: true
        default: 'false'

env:
  MAVEN_ARGS: "--batch-mode --no-transfer-progress"
  MAVEN_GPG_PASSPHRASE: ${{ secrets.MVN_GPG_KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Disabling shallow clone is recommended for improving relevancy of reporting
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/java-maven-action
        with:
          gpg-key: ${{ secrets.MVN_GPG_PRIVATE_KEY }}
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn ${MAVEN_ARGS} verify

  do-maven-release:
    needs: build
    if: ${{ github.event.inputs.do-release == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.release-step.outputs.release_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ADMIN_TOKEN }}
      - uses: ./.github/workflows/actions/java-maven-action
        with:
          gpg-key: ${{ secrets.MVN_GPG_PRIVATE_KEY }}
      - name: Create framework relocation notice release
        id: release-step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONATYPE_CENTRAL_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
          SONATYPE_CENTRAL_USERNAME: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
        run: |
          RELEASE_VERSION=4.0.0
          echo "Release version=$RELEASE_VERSION"
          mvn ${MAVEN_ARGS} clean deploy -DskipTests -Ppackage-deployment
